### PR TITLE
Feature/externs defines now sorted structures

### PR DESCRIPTION
**Pull request by mP1**

### CODE REVIEW

**Comment by mP1** [comment]
Ive included a commit 2225dc2 from another P/R to avoid conflicts.
This is just a few minor improvements to improve tidyness and readability of the source.

**Comment by niloc132** [comment]
Please rebase to remove extra changes from this one.

Entrypoint definition order may well matter, since it will dictate the order that JS is executed at runtime - this is equivalent to reordering statements in a given method (except it is the order of the top level code in the file).

**Comment by mP1** [comment]
k will revert the entry point "sorting" i added and rebase.

**Comment by mP1** [comment]
@niloc132 

rebased: DONE
removed entryPoint "sorting" DONE.

**Pull request merged**
