### PR TITLE
CachedProject computeIfAbsent race fix (ConcurrentModificationException)

### PR DESCRIPTION
**Pull request by mP1**
- replace Collections.synchronized(new HashMap) which ConcurrentHashMap, periodically failed with ConcurrentModificationException

### CODE REVIEW

**Comment by mP1** [comment]
This solves the following ConcurrentModificationException which must have periodically or more often failed for other people due to multiple threads trying to update a `Collections.synchronized(HashMap)` which isnt properly threadsafe.

```java
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
        at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2671)
        at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:224)
        at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:296)
        at net.cardosi.mojo.cache.CachedProject.jscompWithScope(CachedProject.java:322)
        at net.cardosi.mojo.cache.CachedProject.registerAsApp(CachedProject.java:212)
        at net.cardosi.mojo.BuildMojo.execute(BuildMojo.java:131)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

**Comment by niloc132** [comment]
Thanks! How are you reproducing this?

Different JDKs also seem to respond differently based on how threading is currently set up, so I'm pretty sure I'm going to have to take another pass at this all and rebuild it at least one more time.

**Comment by mP1** [comment]
@niloc132 

Im not sure of the best answer about reproducing this as I tried a few JDKs mostly 9 and 10 and it always seem to pop up on a very small sample I was using.

The code is just wrong and should never have worked, and given ConcurrentHashMap almost by definition cant throw ConcurrentHashMap in all put scenarios it cant hurt to accept this PR.  I also dont know why nobody else has complained about this issue, it seems to me it must have happened to other people.

I dont have a good answer for unit testing multi threading issues like this, except as you mention to try rebuilding something a few times, either way this must be an improvement by definition of using CHM :)

**Comment by niloc132** [comment]
ConcurrentHashMap didn't suffer from CMEs, but it did deadlock within the computeIfAbsent calls, since some entries wait on other entries, and especially with newer JDKs the default ForkJoinPool is apparently sized in a very different way than Java 8, resulting in not nearly enough threads to run while those blocked threads waited. It only affects projects with enough dependencies to exhaust the default thread pool. I hadn't hit CMEs at all with the current implementation with either large or small projects, which is why I asked.

The correct fix is to use ForkJoinTasks so that no matter the pool size, paused tasks correctly will run the queued work they are waiting on and keep going. A less correct, but "probably good enough" fix is to just allow a lot more threads than can ever run in parallel, and have some other mechanism to ensure that we don't attempt to have more non-waiting tasks running than we have processors (the rough attempt in the code right now is to have two pools, and attempt to only enqueue "i will wait for other work" tasks in the big one).

I'll try this locally on my battery of projects, but it should be pointed out that 0.9-snapshot is pretty unstable for any project larger than a certain size anyway, since it isn't recursively rebuilding the dependency tree properly after performing replacements. The 0.8-SNAPSHOT is more stable at this time, but has other warts.

**Comment by mP1** [comment]
> ConcurrentHashMap didn't suffer from CMEs, but it did "deadlock" within the computeIfAbsent calls

Well HashMap would also dead lock for the same reason, running out of threads etc.

> ForkJoinPool is apparently sized in a very different way than Java 8, resulting in not nearly enough threads to run while those blocked threads waited

Which means the "size" should be accepted as a parameter with a sensible default. Its just wrong that by chance and too many deps can cause someone unable to compile their project without hacking the "size" in the plugin code etc. Ive got a better idea below, keep reading.

> The correct fix is to use ForkJoinTasks so that no matter the pool size, paused tasks correctly will run the queued work they are waiting on and keep going. 

No, the problem is using a Map of "file" to "promise" that we have now is broken because there is no way to order or "delay" processing of a single file. Processing occurs in the random key order that is HashMap or ConcurrentHashMap, and there is no way to "delay" one entry because it needs to "try again" because another dependency has yet to be run.

My better idea is to use a Queue with a Thread pool (max threads here doesnt matter and only affects speed). Something takes file entries from the pool, if an individual file-entry requires something that has yet to be processed etc, then it can "add" itself to the end of the queue, and it should be retried again after the "dependency" has run.

I will be honest I havent looked hard at the code and Im not sure who "finds" and spawns more tasks for dependencies, but again the queue idea is easy enuff, just add more stuff to the end of the queue.

Naturally processing continues until the queue is empty or it appears stalled and isnt making any progress after running thru everything in a queue and starting again etc.

Does this sound right ? Want me to give it a go ?

**Comment by niloc132** [comment]
Unfortunately, the change that brought us to this point got squashed before it landed, so I don't have more of my notes on this. This section of code is getting a pretty big overhaul (to deal with the "why don't replacements happen across the whole graph" issue), i'll import this change directly over there, so that just in case it doesn't properly survive the merge here, it will be sure to be back again.

Semantics are different though - being just dumbly synchronized on every method, you can't get the deadlock since other threads have to wait for their turn to read or write from the steps map (especially the computeIfAbsent call, since now no other thread can read or write while that thread is considering what to insert). 

As to the size of the default FJP, yes - the JVM lets you specify it on startup as a system property, but that's a bit arcane. Better to use the FJP "properly" (not using CF with it, apparently), or make my own pools custom tailored for their purpose.

At some level yeah its a queue - the issue is that the way things are structured now, some code is written to block until its dependencies are satisfied. I've gotten a bit too comfortable in other projects with Promises, so tried to use CompletableFuture in the same way, and that's where we are. Large projects (both "deep" and "wide" trees of dependencies) with an extremely restricted thread count will help ensure that the old deadlock doesn't creep back in again. A queue works as long as you have a way to guarantee order - no item can come before its dependencies, which is what the current approach solves, enabling each task to explicitly wait on its dependencies, and asking an item to build involves first resolving (and, if you are in "watch" mode, possibly recompiling those dependencies as appropriate).

So yes, will merge, but will require more testing of the solution than "works on my machine" first ;), especially since this was tried previously and failed (and lacking a test case that demonstrates failure for you).

**Comment by mP1** [comment]
> Semantics are different though - being just dumbly synchronized on every method, you can't get the deadlock since other threads have to wait for their turn to read or write from the steps map (especially the computeIfAbsent call, since now no other thread can read or write while that thread is considering what to insert).

> As to the size of the default FJP, yes - the JVM lets you specify it on startup as a system property, but that's a bit arcane. Better to use the FJP "properly" (not using CF with it, apparently), or make my own pools custom tailored for their purpose.

A global system property thing is a hack and might very well screw other parts of maven/plugins. For me the simplest basic solution is to make a parameter for this plugin.

> At some level yeah its a queue - the issue is that the way things are structured now, some code is written to block until its dependencies are satisfied.

The idea of blocking is broken while inside a thread is broken, as you sort of implied in a very large graph system you are going to have lots and lots of promises waiting for other stuff.

Using a REAL queue not a looping over a map is a much safer and simpler way to solve this problem, and it avoids any worry about running out of threads etc.

>  A queue works as long as you have a way to guarantee order - no item can come before its dependencies, which is what the current approach solves,

No the queue approach would have logic to so that something requiring an unprocessed dep, would simply abort and add itself to the end. Let me give a simple example for reference.

```
A3 requires B2 requires C1

queue = A3, B2, C1

try A3 
aborts because it requires B2 // doesnt matter B2 is itself incomplete.
queue = B2, C1
tryAgainQueue = A1

try B2
aborts because it requires C1
queue = C1
tryAgainQueue = A1, B2

try C1
success

queue = tryAgainQueue
tryAgainQueue = EMPTIED

try A3
aborts again because it requires B2
queue = B2
tryAgainQueue = A3

try B2
success it required C1 and its done
queue = EMPTY
tryAgainQueue = A3

queue = tryAgainQueue = A1
tryAgainQueue = EMPTY

try A3
success it required B2 and its done
queue = EMPTY
tryAgainQueue = EMPTY

therefore all DONE!
```

The only thing i havent examined is how something knows it has unprocessed dependencies, if the current code has logic to determine this then refactoring my idea should be simple enough.

> A queue works as long as you have a way to guarantee order - no item can come before its dependencies, which is what the current approach solves, enabling each task to explicitly wait on its dependencies, and asking an item to build involves first resolving (and, if you are in "watch" mode, possibly recompiling those dependencies as appropriate).

Sorry to repeat, the whole problem is waiting while using a thread, my way waiting files are simply added to a tryAgainQueue which eventually gets processed. Basically the system keeps trying until both lists run out etc with smarts to handle endless loops.

Will give it a go soon.

**Comment by mP1** [comment]
My only concern with my approach is how one file knows it has to wait for dependencies to be processed, but hey it cant be that hard to leverage the existing code that "knows" or "determines" this.

**Comment by niloc132** [comment]
Quite likely that if it was started today from nothing, knowing what I already know, I could do better than I've done. The code that exists so far covers up a wide variety of issues I ran into, and the shortcuts to get to working code end up being around much longer than I'd like. Ya know, software development at its finest ;).

Minor point, we're not tracking per-file dependencies at this time (though @mdproctor would like us to look into this I know), but this dependency graph is the standard maven dependencies between modules/artifacts/etc. When a goal like `j2cl:watch` is invoked on a multi-module project, it watches all applicable modules for changes - when any one is changed in some way it is marked as dirty, and the "downstream" app is told to start a new compile, collecting changes and recompiling only what is necessary as it goes. 

Off the shelf code to detect dependencies between .java files will not work here, since we're not using the standard java ABI, but need to also detect changes to jsinterop annotations as well to know when to regenerate. Those changes are just as important now as renaming methods, changing type hierarchy, etc, and I'm aware of no project which is capable of that today (including this one).

The current impl is certainly isomorphic to a queue where dependencies are traversed and enqueued in such a way that multiple workers can pull tasks off where all dependencies are already satisfied (probably more "heap" shaped than queue now that I think about it, since near the end the work will probably necessarily become singly threaded). The fact that it is CompletableFuture-based is just a historical detail, but a necessary way to build this.

Competing tools/workflows/forks welcome, I'm a big fan of competition to better the whole ecosystem.

**Comment by niloc132** [comment]
Join us over in https://gitter.im/vertispan/j2cl for more active discussion on this if you do want to compete/collaborate - both are equally welcome, you sound like you're interested in this and have thought a fair bit about the way this would look if you were king.

**Comment by FrankHossfeld** [comment]
I ran in this issue during the update of the GWT modules.

To trigger the `j2cl:test` goal using the Maven tool window from IntelliJ works fine. Using the same command from the command line, `j2cl:test` fails.

The main difference between both envirements is, that Maven runs on OpenJDK 8 inside IntelliJ and inside the terminal Maven it uses OpenJDK 11.

**Comment by niloc132** [comment]
Here's the deadlock this fix causes:
```
"main" #1 prio=5 os_prio=0 tid=0x00007f81ec00a800 nid=0x14c54 runnable [0x00007f81f36c9000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1718)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:221)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:293)
	at net.cardosi.mojo.cache.CachedProject.hash(CachedProject.java:687)
	at net.cardosi.mojo.cache.CachedProject.lambda$getOrCreate$5(CachedProject.java:226)
	at net.cardosi.mojo.cache.CachedProject$$Lambda$16/1306067302.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x0000000720a18db8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:221)
	at net.cardosi.mojo.cache.CachedProject.getOrCreate(CachedProject.java:293)
	at net.cardosi.mojo.cache.CachedProject.jscompWithScope(CachedProject.java:319)
	at net.cardosi.mojo.cache.CachedProject.registerAsApp(CachedProject.java:209)
	at net.cardosi.mojo.WatchMojo.execute(WatchMojo.java:135)

```

To repro, try java 8 with this fix on https://github.com/react4j/react4j-todomvc/tree/raw_maven_j2cl with the `j2cl:watch` goal. It seems to fail every time.

**Comment by mP1** [comment]
@niloc132 

Im going to guess (dont actually know) that the absent function blocks whilst it is busy, making this fix broken when possibly (cycles???) are present. IMHO the job scheduling thing used in this version is broken, and not sure if its worth fixing (v0.9) especially since you have reverted back to the previous version (v0.8)

**Comment by niloc132** [comment]
Agreed that this is broken, but it has been broken since the first revision, so not something that reverting would be effective to fix. This deadlock (which happens every time, regardless of JRE version, in the right conditions) is why I avoided ConcurrentHM to begin with, as detailed earlier in this thread.

The real fix is a better structure for the DAG of dependencies. I have a solution whiteboarded which should encourage better multi-core performance, but it isn't complete yet.

Closing this PR since it isn't an effective way to solve this bug, but I opened #18 to track this issue, and to see about a new fix.

**Pull request closed without merging**
